class RecordField

  ADDRESS_STREET_1 = :ADDRESS_STREET_1
  ADDRESS_STREET_2 = :ADDRESS_STREET_2
  ADDRESS_CITY = :ADDRESS_CITY
  ADDRESS_STATE = :ADDRESS_STATE
  ADDRESS_POSTAL_CODE = :ADDRESS_POSTAL_CODE
  ADDRESS_FULL = :ADDRESS_FULL
  AMOUNT_CONTRIBUTION_TRADITIONAL = :AMOUNT_CONTRIBUTION_TRADITIONAL
  AMOUNT_CONTRIBUTION_TRADITIONAL_DOLLER = :AMOUNT_CONTRIBUTION_TRADITIONAL_DOLLER
  AMOUNT_CONTRIBUTION_ROTH = :AMOUNT_CONTRIBUTION_ROTH
  AMOUNT_CONTRIBUTION_ROTH_DOLLER = :AMOUNT_CONTRIBUTION_ROTH_DOLLER
  AMOUNT_MATCH = :AMOUNT_MATCH
  AMOUNT_MATCH_TRADITIONAL = :AMOUNT_MATCH_TRADITIONAL
  AMOUNT_MATCH_ROTH = :AMOUNT_MATCH_ROTH
  AMOUNT_MATCH_SAFE_HARBOR = :AMOUNT_MATCH_SAFE_HARBOR
  AMOUNT_NON_ELECTIVE_SAFE_HARBOR = :AMOUNT_NON_ELECTIVE_SAFE_HARBOR
  AMOUNT_PAY_GROSS = :AMOUNT_PAY_GROSS
  AMOUNT_LOAN_PAYMENTS = :AMOUNT_LOAN_PAYMENTS
  AMOUNT_LOAN_PAYMENTS1 = :AMOUNT_LOAN_PAYMENTS1
  AMOUNT_LOAN_PAYMENTS2 = :AMOUNT_LOAN_PAYMENTS2
  AMOUNT_PROFIT_SHARING = :AMOUNT_PROFIT_SHARING
  DATE_BIRTH = :DATE_BIRTH
  DATE_HIRE = :DATE_HIRE
  DATE_REHIRE = :DATE_REHIRE
  DATE_TERMINATION = :DATE_TERMINATION
  EMAIL = :EMAIL
  PHONE_NUMBER = :PHONE_NUMBER
  GENDER = :GENDER
  HOURS = :HOURS
  HOURS_REGULAR = :HOURS_REGULAR
  HOURS_OVERTIME = :HOURS_OVERTIME
  MARITAL_STATUS = :MARITAL_STATUS
  NAME_FIRST = :NAME_FIRST
  NAME_LAST = :NAME_LAST
  NAME_FULL = :NAME_FULL
  NAME_MIDDLE_INITIAL = :NAME_MIDDLE_INITIAL
  SSN = :SSN
  DIVISION_ID = :DIVISION_ID
  PARTICIPANT_ID = :PARTICIPANT_ID

  ADP_RUN_EARNING_DESCRIPTION = :ADP_RUN_EARNING_DESCRIPTION
  ADP_RUN_DEDUCTION_DESCRIPTION = :ADP_RUN_DEDUCTION_DESCRIPTION
  ADP_RUN_DEDUCTION_AMOUNT = :ADP_RUN_DEDUCTION_AMOUNT
  ADP_RUN_DEDUCTION_TYPE = :ADP_RUN_DEDUCTION_TYPE
  AMOUNT_LOAN_PAYMENTS_HASH = :AMOUNT_LOAN_PAYMENTS_HASH
end